[toolchain]

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
marketplace = "6SoLn7evYbz9YPHCyh5CsVifCax3WhZwUFoc9Vyaoqoi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
